### PR TITLE
`augment.mvgam` tidying method added

### PR DESCRIPTION
**Pull request by swpease**
Implemented an `augment` method for mvgam objects, one of the "tidying" methods. Largely diverged from the set of recommendations in [generics](https://web.archive.org/web/20240520145739/https://www.tidymodels.org/learn/develop/broom/#implementing-the-augment-method).

### CODE REVIEW

**Comment by swpease** [comment]
A few notes:
  - I used the generics package per the [tidymodels suggestion](https://www.tidymodels.org/learn/develop/broom/).
  - I put both generics and tibble in Imports, because they are both dependencies of dependencies anyway: `sort(tools::package_dependencies(packages = "mvgam", recursive = TRUE)$mvgam)`. 
  - I didn't follow the tidymodels suggestion on implementation very closely.

I just did what seemed sensible to me. In any case, I'll need to actually write some more documentation.

**Review by nicholasjclark — CHANGES_REQUESTED** [review]
Thanks so much for this @swpease. Overall this looks great but there is one small issue that needs a bit of work: mvgam can handle data that are in a `list` rather than a `dataframe`, so the `obs_data` slot may be in `list` format as well (see `mvgam:::mvgam_example5$obs_data` for an example of this). Would you mind editing `augment.mvgam` to handle list observations? Unfortunately this will mean that the output will also be a `list` in those special cases, but I think that is fine for now

**Comment by swpease** [comment]
It looks like `as_tibble` handles lists just fine, e.g. 

`identical(mvgam_example5$obs_data, as.list(tibble::as_tibble(mvgam_example5$obs_data)))`

, but do you explicitly want a list returned if the data was input as a list? Maybe there's some edge case I'm missing. 

I see also that the covariates can be a matrix, which `as_tibble` does handle, but each column name is like "cov[, 1]", "cov[, n]". Example:

```
miss_dat <- list(outcome = rnorm(10),
  series = factor('series1',
  levels = 'series1'),
  time = 1:10)
miss_dat$cov <- matrix(rnorm(50), ncol = 5, nrow = 10)

out = mvgam(outcome ~ cov,
  data = miss_dat,
  family = gaussian(),
  backend = 'cmdstanr')

x = augment(out)
```

This isn't the first time I've wished R was statically typed :neckbeard:

**Comment by nicholasjclark** [comment]
Thanks @swpease. I think in general it would be better if a `list` is returned whenever `data` was supplied as a such, just to ensure there are no surprises for the users who will then want to use those data with the added fits and residuals to make diagnostic plots. As long as this is explicitly documented in the function docs then that would be better in my opinion

**Comment by swpease** [comment]
Alright, method operates on lists. I'm not sure what would be useful tests, so I've got a couple simple ones. Can't think of anything that doesn't seem brittle and unhelpful. Also, unsurprisingly I messed up my git workflow, so I kinda want to just make a new branch with a single commit and copy over the changes.

**Comment by nicholasjclark** [comment]
Excellent thanks @swpease. I've merged this now and added you as a contributor to the DESCRIPTION. Please check and let me know if more details should be added (i.e. ORCID id or email address). I really appreciate the help! Will need to think about adding `glance` and `tidy` support soon as well for the whole package

**Comment by swpease** [comment]
Here's my shiny new ORCID ID: 0009-0006-8977-9285

I had initially looked at implementing `glance`, since it's first in the list, until I scrolled and scrolled through `summary`, and thought, let's see how `augment` goes.

**Comment by nicholasjclark** [comment]
Thanks @swpease. Yes completely agree, that function in particular needs a major overhaul first. I've added your ORCID now, really appreciate the help

**Pull request merged**
